SELECT NAME , PRICE
FROM PRODUCTS
WHERE CATGORY= 'ELECTRONICS'
ORDER BY PRICE DESC
LIMIT 3;

SELECT CATEGORY,
COUNT(*)AS TOTAL_PRODUCTS,
AVG(PRICE)AS AVERAGE_PRICE,
SUM (PRICE*STOCK_QUANTITY)AS TOTAL_STOCK_VALUE
FROM PRODUCTS
GROUP BY CATEGORY
HAVING COUNT(*)>5

SELECT
UPPER(NAME) AS UPPER_NAME,
LEFT(NAME,10)AS SHORT_DESC,
DATEDIFF (NOW(),DATE_ADDED)AS DAYS_SINCE_ADDED
FROM PRODUCTS;

ALTER TABLE PRODUCTS
ADD DISCOUNT_RATE DECIMAL(5,2);
UPDATE PRODUCTS
SET DISCOUNT_RATE = 0.10
WHERE CATEGORY = 'ACCESSORIES';
DELETE FROM PRODUCTS
WHERE STOCK_QUANTITY= 0;
DROP TABLE OLD_INVENTORY;










