let x = 7;
let y = 5;
console.log(x + y);
console.log(x - y);
console.log(x * y);
console.log(x / y);
console.log(x % y);
console.log(x ** y);
console.log((x + y) * 2);
console.log((x - 2) * (y + 1));
console.log("@@@@@@@@@@@@@@@@@@@@@@@");
let a = 10;
let b = "Hello";
let c = true;
let d = null;
let e = undefined;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
console.log(typeof d); 
console.log(typeof e);
console.log("@@@@@@@@@@@@@@@@@@@@@");
let q = 7;
let z = 5;
console.log(q == z);
console.log(q != z);
console.log(q > z);
console.log(q < zy);
console.log(q >= zy);
console.log(q <= z);
console.log(q && z);
console.log("@@@@@@@@@@@@@@@@@@@@@@@");
let r = true;
let n = false;
console.log(r && n);
console.log(r || n);
console.log(!r);
console.log(!r);
console.log((r && n) || r);
console.log("@@@@@@@@@@@@@@@@@@@@@");
let name = "Ali";
let str = " your age ";
console.log(name + str);
console.log("Age is " + 20);
console.log("Hello " + name);
console.log((10 + 20) + " years");
console.log("Age: " + (10 + 20));
console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@@");
let m = 5;
console.log(m++);
console.log(m);
console.log(++m);
console.log(m--);
console.log(m);
console.log(--m);
console.log(m += 3);
console.log(m -= 2);
console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@");
let xx = 10;
console.log(xx++);
console.log(xx);
console.log(++xx);
console.log(xx--);
console.log(xx);
console.log("@@@@@@@@@@@@@@@@@@@@@@");
let aa = 4;
let bb = 6;
let cc = 2;
console.log(aa + bb * cc);
console.log((aa + bb) * cc);
console.log(bb / cc + aa);
console.log(aa + bb == cc);
console.log(aa <bb && bb > cc);
console.log("@@@@@@@@@@@@@@@@@@@@@@@@@@@@");